Add smart contract feature example blog post
vendia/blog pull request #124
Opened 2022-05-25 16:29 UTC by james-vendia

2022-05-25 18:04 UTC, brian-vendia requested changes

2022-05-25 20:34 UTC, james-vendia commented on posts/2022-05-25-smart-contract-feature-example.md
> +After the Lender and the Servicer create a Uni to share home loan information with each other, they want to maintain a high level of data quality.  Specifically, the Lender wants to ensure the Servic
Addressed in latest

2022-05-25 23:35 UTC, db-vendia commented on posts/2022-05-25-smart-contract-feature-example.md
> +Select the `validation-smart-contract` to view its details, including the ability to manually invoke the smart contract.  Next, click the `Invoke` button in the upper right and provide a valid `loanI
Nitpick, but you you say "click the `Invoke` button in the upper right" but in the modal (which is not the screen to which you are referring to, but is the screen highlighted in the screenshot) the Invoke button is in the lower right. Is it worth adding another screenshot to show the Invoke button in the upper right then this screenshot showing the input into the SC?

2022-05-25 23:36 UTC, db-vendia commented on posts/2022-05-25-smart-contract-feature-example.md
> +Select the `validation-smart-contract` to view its details, including the ability to manually invoke the smart contract.  Next, click the `Invoke` button in the upper right and provide a valid `loanI
The rest looks good.

2022-05-26 14:04 UTC, james-vendia commented on posts/2022-05-25-smart-contract-feature-example.md
> +Smart contracts can be used for a variety of purposes, including data validation, computation, and enrichment.  The recently published [smart contract feature example](https://github.com/vendia/examp
```suggestion
Smart contracts can be used for a variety of purposes, including data validation, computation, and enrichment.  The recently published [smart contract feature example](https://github.com/vendia/examples/blob/main/features/share/smart-contracts/README.md) provides a step-by-step guide to create and invoke a set of smart contracts, each demonstrating slightly different interaction patterns and smart contract composition approaches.  Using smart contracts allows data _and code_ to be shared and ledgered for real-time awareness and full transparency across a network of Uni participants.
```

2022-05-26 14:13 UTC, merged