open beta announcement blog post
vendia/blog pull request #44
Opened 2021-12-08 16:28 UTC by db-vendia

2021-12-08 19:27 UTC, brian-vendia requested changes
I really like where this is headed!

2021-12-08 19:27 UTC, brian-vendia commented on posts/2021-12-09-announcing-new-features.md
> +![](https://user-images.githubusercontent.com/92179243/145060082-56557805-7708-4a26-8818-8dcfb95ceb78.png "smart contracts")
```suggestion
![smart contracts](https://user-images.githubusercontent.com/92179243/145060082-56557805-7708-4a26-8818-8dcfb95ceb78.png)
```

2021-12-08 19:27 UTC, brian-vendia commented on posts/2021-12-09-announcing-new-features.md
> +![](https://user-images.githubusercontent.com/92179243/145060323-52c8b712-acc6-4fea-8a03-eff794849c63.png "Entity Explorer")
```suggestion
![Entity Explorer](https://user-images.githubusercontent.com/92179243/145060323-52c8b712-acc6-4fea-8a03-eff794849c63.png)
```

2021-12-08 19:27 UTC, brian-vendia commented on posts/2021-12-09-announcing-new-features.md
> +![](https://user-images.githubusercontent.com/92179243/145060474-7b676775-746e-4493-95be-adb37ce1f059.png "Edit a entity explorer")
```suggestion
![Edit an entity](https://user-images.githubusercontent.com/92179243/145060474-7b676775-746e-4493-95be-adb37ce1f059.png)
```

2021-12-08 19:27 UTC, brian-vendia commented on posts/2021-12-09-announcing-new-features.md
> +![](https://user-images.githubusercontent.com/92179243/145244534-292321e8-19a4-4e04-90cf-d7c9ef8143e4.png)
```suggestion
![Azure node](https://user-images.githubusercontent.com/92179243/145244534-292321e8-19a4-4e04-90cf-d7c9ef8143e4.png)
```

2021-12-08 19:27 UTC, brian-vendia commented on posts/2021-12-09-announcing-new-features.md
> +Clicking into the ID for any of the rows, will open the ability to edit, delete or view the full history of that entry. You have full control over which users can view, edit or delete data through th
```suggestion
Clicking into the `_id` for any of the rows, will open the ability to edit, delete or view the full history of that entry. You have full control over which users can view, edit or delete data through the Entity Explorer. 
```

2021-12-08 19:27 UTC, brian-vendia commented on posts/2021-12-09-announcing-new-features.md
> +We are also announcing that Vendia Share is now available as a SaaS offering, with pricing that scales from single users through large enterprises. All pricing plans include the new features, along w
```suggestion
We are also announcing pricing that meets customers' demand and allows them to scale their usage from single users through large enterprises. All pricing plans include the new features, along with the established capabilities for building and running highly scalable, fault-tolerant, cross-cloud, multi-account, multi-region, multi-party applications. Share is available in three plans: Starter, Individual, and Enterprise. Starter is our free plan that offers developers generous limits to test Vendia at no cost. The Individual plan removes most of the limits of the Starter plan and starts at $99 per month. The Starter and Individual plans are currently in beta and available for all customers. For more information, see the [pricing page](https://www.vendia.net/pricing). 
```

2021-12-08 21:51 UTC, brian-vendia commented
@db-vendia please talk with Kevin regarding the release date. I'm not sure when this post should go out so you should adjust the publish date accordingly.

2021-12-09 00:06 UTC, james-vendia approved these changes
Looks good!

2021-12-09 00:07 UTC, merged